#/home/u/altera/13.1/quartus/eda/sim_lib/altera_mf.v
#/mnt/c/intelFPGA_lite/19.1/quartus/eda/sim_lib/altera_mf.v

#../altera_mf.v
../../rtl/cpu7b/simulation/altera_mf.v


../../rtl/cpu7b/rtl/alu.v 
../../rtl/cpu7b/rtl/branch.v 
../../rtl/cpu7b/rtl/common.vh 
../../rtl/cpu7b/rtl/cpu7_csr_byplog.v 
../../rtl/cpu7b/rtl/cpu7_csr.v 
../../rtl/cpu7b/rtl/cpu7_exu_eclbyplog_rs1.v 
../../rtl/cpu7b/rtl/cpu7_exu_eclbyplog.v 
../../rtl/cpu7b/rtl/cpu7_exu_ecl.v 
../../rtl/cpu7b/rtl/cpu7_exu.v 
../../rtl/cpu7b/rtl/cpu7_ifu_dec.v 
../../rtl/cpu7b/rtl/cpu7_ifu_fdp.v 
../../rtl/cpu7b/rtl/cpu7_ifu_imd.v 
../../rtl/cpu7b/rtl/cpu7_ifu_incr30.v 
../../rtl/cpu7b/rtl/cpu7_ifu.v 
../../rtl/cpu7b/rtl/cpu7_nocache.v 
../../rtl/cpu7b/rtl/decoded.vh 
../../rtl/cpu7b/rtl/decoder.v 
../../rtl/cpu7b/rtl/mul32x32.v
../../rtl/cpu7b/rtl/mul64x64.v 
../../rtl/cpu7b/rtl/reg_file.v 
../../rtl/cpu7b/rtl/swrvr_clib.v 
../../rtl/cpu7b/rtl/swrvr_dlib.v 
../../rtl/cpu7b/rtl/defines.vh 
../../rtl/cpu7b/rtl/axi_sram_bridge.v 
../../rtl/cpu7b/rtl/axi_interface.v 
../../rtl/cpu7b/rtl/sram.v 
../../rtl/cpu7b/rtl/cpu.v 
../../rtl/cpu7b/rtl/cpu7_csr_timer.v
../../rtl/cpu7b/rtl/c7blsu/rtl/c7blsu.v
../../rtl/cpu7b/rtl/c7blsu/rtl/decode.vh
../../rtl/vga/vga640x480.v 
../../rtl/vga/vgaram.v 
../../rtl/vga/text80x25.v 
../../rtl/vga/hvsync.v 
../../rtl/vga/vgatextram.v 
../../rtl/vga/chrom.v 
../../rtl/ram_bridge.v 
../../rtl/pll.v
../../rtl/amba_axi_m2s3.v
../../rtl/peripherals/peripherals.v
../../rtl/peripherals/uart/uart.v
../../rtl/soc2_top.v 
../../tb/soc2_test6_spaceinvaders_top_tb.v

